aws:
  credentials:
    access-key: test_access_key
    secret-key: test_secret_access_key
  s3:
    endpoint: http://s3.${LOCALSTACK_HOST}:4566/
  dynamodb:
    endpoint: http://${LOCALSTACK_HOST}:4566/
  sqs:
    endpoint: http://${LOCALSTACK_HOST}:4566/000000000000
  region: eu-central-1